[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[plugins]]
  package = "netlify-plugin-minify-html"
 
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"
